import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/header'
import 'react-toastify/dist/ReactToastify.css';
import {ToastContainer, toast} from 'react-toastify';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Todo List APP',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">

      
      <body className={inter.className}>

        <ToastContainer toastStyle={{
          borderRadius:'15px',
          textAlign:'center',
          fontWeight:'bold'
        }} position={"bottom-left"}/>

          <Header/>
          
          {children}

      </body>
    </html>
  )
}
